export GOPATH="${HOME}/.go"
export GOROOT="$(dirname $(dirname $(which brew)))/opt/go/libexec"
export PATH="$PATH:${GOPATH}/bin:${GOROOT}/bin"
mkdir -p "${GOPATH}"
mkdir -p "${GOPATH}/src/github.com"
