#  zsh-autosuggestions
#)

# source $ZSH/oh-my-zsh.sh

#if [[ -e /usr/share/zsh/manjaro-zsh-config ]]; then
#  source /usr/share/zsh/manjaro-zsh-config
#fi          

source <(/usr/bin/starship init zsh --print-full-init)

source ~/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh
source ~/.zshrc.aliases
source ~/.zshrc.ssh-agent

source /usr/share/nvm/init-nvm.sh

export PATH=/home/simme/.cargo/bin:$PATH
export GPG_TTY=$(tty)

autoload -Uz compinit
zstyle ':completion:*' menu select
fpath+=~/.zfunc
