# zmodload zsh/zprof

export ZSH="$HOME/.oh-my-zsh"
export ZSH_DISABLE_COMPFIX=true
export TERM='xterm-256color'

source $ZSH/oh-my-zsh.sh

ssh-add -K ~/.ssh/id_rsa 2>/dev/null

typeset -U config_files
config_files=(~/.zsh/*.zsh)

for file in ${config_files}
do
  source $file
done

source <(kubectl completion zsh)
complete -F __start_kubectl k
# zprof
