live_config_reload: true
alt_send_esc: true
shell:
    program: /bin/zsh

cursor:
  style: Block
  unfocused_hollow: false

scrolling:
  history: 10000
  multiplier: 3

window:
  decorations: transparent
  dynamic_padding: false
  padding:
    x: 10
    y: 30

colors:
  primary:
    background: '0x2E3440'
    foreground: '0xD8DEE9'
  cursor:
    text: '0x2E3440'
    cursor: '0xD8DEE9'
  normal:
    black: '0x3B4252'
    red: '0xBF616A'
    green: '0xA3BE8C'
    yellow: '0xEBCB8B'
    blue: '0x81A1C1'
    magenta: '0xB48EAD'
    cyan: '0x88C0D0'
    white: '0xE5E9F0'
  bright:
    black: '0x4C566A'
    red: '0xBF616A'
    green: '0xA3BE8C'
    yellow: '0xEBCB8B'
    blue: '0x81A1C1'
    magenta: '0xB48EAD'
    cyan: '0x8FBCBB'
    white: '0xECEFF4'

key_bindings:

  - key: N
    mods: Command
    action: SpawnNewInstance

  - key: Return
    mods: Control
    action: ToggleSimpleFullscreen

  - key: Left
    mods: Alt
    chars: "\x1bb"
  
  - key: Right
    mods: Alt
    chars: "\x1bf"
