# zmodload zsh/zprof

autoload -Uz compinit

setopt EXTENDEDGLOB
for dump in $HOME/.zcompdump(#qN.m1); do
  compinit
  if [[ -s "$dump" && (! -s "$dump.zwc" || "$dump" -nt "$dump.zwc") ]]; then
    zcompile "$dump"
  fi
done
unsetopt EXTENDEDGLOB
compinit -C

export ZSH_DISABLE_COMPFIX="true"
export TERM='xterm-256color'

ssh-add -K ~/.ssh/id_rsa 2>/dev/null

typeset -U config_files
config_files=(~/.zsh/*.zsh)

for file in ${config_files}
do
  source $file
done

# zprof
